### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bitog** [mimicmobile/flask-telegram-relay-bot#1]
Hi there,

I am getting the following error":

```
Traceback (most recent call last):
  File "/home/fs/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fs/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fs/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fs/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fs/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fs/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fs/Bots/Telegram/flask-telegram-relay-bot/bot/main.py", line 52, in relay
    utils.send_message(chat_id=chat_id, text=parsed_json['message'])
KeyError: 'message'
```

**Comment by corcoran** [comment]
It looks like your POST payload JSON doesn't contain a `message` key. Please post the request in its entirety.
